# Generated by Django 5.0.7 on 2024-08-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kazani", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="description",
            new_name="about_me",
        ),
        migrations.AddField(
            model_name="user",
            name="extra_seo",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
