# Generated by Django 5.0.7 on 2024-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kazani", "0002_rename_description_user_about_me_user_extra_seo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="extra_seo",
        ),
        migrations.AlterField(
            model_name="user",
            name="about_me",
            field=models.URLField(blank=True, null=True),
        ),
    ]
