# Generated by Django 5.0.7 on 2024-07-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
