# Generated by Django 5.0.7 on 2024-07-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_slug_alter_article_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
