# Generated by Django 5.0.7 on 2024-07-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_article_draft_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="modifed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
