# Generated by Django 5.0.7 on 2024-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_created_alter_article_modifed"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(default="", max_length=480),
        ),
    ]
