# Generated by Django 5.0.7 on 2024-08-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_article_seo_alter_article_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="seo",
        ),
    ]
