# Generated by Django 5.0.7 on 2024-08-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_article_seo"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
