# Generated by Django 5.0.7 on 2024-08-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_article_options_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
