# Generated by Django 5.0.7 on 2024-08-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_article_head_article_script"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(
            model_name="article",
            name="is_homepage",
        ),
        migrations.AddField(
            model_name="article",
            name="is_hidden",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="article",
            name="page_url",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="head",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="script",
            field=models.TextField(blank=True, default=""),
        ),
    ]
