# Generated by Django 5.0.7 on 2024-08-07 20:05

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_comment_options_remove_article_is_homepage_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_indexed",
            field=models.BooleanField(
                default=False,
                help_text="Whether to allow search engines to index this page.",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.JSONField(help_text="Content of the page"),
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(
                default="",
                help_text="Description of the page for the article list and search engines.",
                max_length=480,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="head",
            field=models.TextField(
                blank=True, default="", help_text="HTML that is inserted into <head>"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_draft",
            field=models.BooleanField(
                default=True,
                help_text="Honestly does nothing but shows DRAFT on the page.",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_hidden",
            field=models.BooleanField(
                default=True, help_text="Hides the page from the article list."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="no_container",
            field=models.BooleanField(
                default=False,
                help_text="Remove everything but the navigation and footer.",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="page_url",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Absolute path to show page at (/ for homepage, /about, etc.)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="script",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Javascript code that goes at the end of body.",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for (eventual) searching and for search engines.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
