# Generated by Django 5.0.7 on 2024-08-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_article_is_indexed_alter_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="extra_seo",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
