# Generated by Django 5.0.7 on 2024-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_article_extra_seo"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="override_seo",
            field=models.BooleanField(default=False),
        ),
    ]
