# Generated by Django 5.0.7 on 2024-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_article_content_type_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_type",
            field=models.IntegerField(
                choices=[(1, "Json"), (2, "Markdown"), (3, "Html")], default=2
            ),
        ),
    ]
