# Generated by Django 5.0.7 on 2024-10-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_article_comments_enabled_alter_article_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
