# Generated by Django 5.0.7 on 2024-11-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_upload_alter_article_comments_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="ident",
            field=models.CharField(
                default="",
                help_text="Identifier for the image. Used to auto-generate the url if it's not specified (/media/ident). Also used to refer to it in Markdown.",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="upload",
            name="path",
            field=models.CharField(
                help_text="Absolute path to serve file at (/media/image.png, etc.)",
                max_length=512,
            ),
        ),
    ]
